# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pWGRM1a0gCFI8dt9hjwTItm6cRcxbKiR
"""

import pandas as pd
baza={
   "FISH":["Ma'rifova Muslimabonu","Toshmatov Toshpo'latjon","Habibullayeva Durdonaxon","Aliyev Ali","Ochildinova Ziyodaxon","Valiyev Vali","Umarova Mavlidaxon","Davlatov Davlatjon ","To'ychiyeva Dilnavozxon","Ahmadov Ahmadjon"  ],
   "YOSHI":[ '18','11','19','15','20','12','18','14','18','16'],
    "Maktabi":[ '17-maktab','1-maktab','19-maktab','42-maktab','18-maktab','3-maktab','17-maktab','5-maktab','20-maktab','2-maktab'   ],
    "Jinsi":['qiz bola',"o'g'il bola",'qiz bola',"o'g'il bola",'qiz bola',"o'g'il bola",'qiz bola',"o'g'il bola",'qiz bola',"o'g'il bola"  ],
    "Manzili":[ "Qo'qon shaxar",'Samarqand shaxar',"Marg'ilon shaxar",'Buxoro shaxar','Toshkent shaxar','Andijon shaxar',"Qo'qon shaxar",'Namangan shaxar',"Farg'ona shaxar",'Xorazm shaxar' ],
}
db=pd.DataFrame(baza)
print(db)

filtr=db[db['Maktabi']=='17-maktab']
print(filtr)

filtr=db[(db['Maktabi']=='17-maktab') & (db['Jinsi']=='qiz bola')]
print(filtr)